name: mkdocs
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
      - name: install dependencies
        run: pip install \
          mkdocs-material \
          mkdocs-glightbox \
      - run: mkdocs gh-deploy --force
